# Generated by Django 4.2.6 on 2023-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(),
        ),
    ]
