# Generated by Django 4.2.6 on 2023-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_expenses', '0002_alter_category_options_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(),
        ),
    ]
